
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
    show-sql: false
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
  application:
    name: fixedasset-manager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # redis token
  redis:
    key:
      prefix:
        userToken: "user:token:"
        passwordError: "user:password:error:"
        permissionRefresh: "user:token:permissionRefresh:"
      expire:
        userToken: 604800 # 7days 7*24*3600
        passwordError: 3600 # 1 Hours
        permissionRefresh: 604800 # 7DAYS 7*24*3600
    allowMultipleLogin: true


mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  #global-config:
  #  db-config:
 #     logic-delete-value: 0
 #     logic-not-delete-value: 1
 #     logic-delete-field: deleted

project:
  database: mysql




